### PR TITLE
CI using TravisCI

### PR DESCRIPTION
**Pull request by artiemq**
Add `py36` to tox envlist and create `.travis.yml`

### CODE REVIEW

**Comment by tholo** [comment]
That looks good to me. Can’t believe I forgot to add py3.6 — did the last few merges using that!

**Comment by jacquerie** [comment]
> That looks good to me.

But you will have to enable this repo on Travis for this to work: https://travis-ci.org/tholo/pytest-flake8. It appears I don't have enough rights to do it myself...

**Comment by tholo** [comment]
It has been enabled — might need a new commit / push to actually build...

**Comment by jacquerie** [comment]
> might need a new commit / push to actually build

Trick: you can close and reopen a PR and it triggers a new build. Let me do that.

**Comment by artiemq** [comment]
Sorry, i merged it.

**Comment by jacquerie** [comment]
> Sorry, i merged it.

It's ok, we actually managed to create a bug in GitHub's UI by simultaneously closing and merging...

**Pull request merged**
