### PR TITLE
fix typo: "it turn" → "in turn"

### PR DESCRIPTION
**Pull request by das-g**

### CODE REVIEW

**Comment by jaraco** [comment]
I've merged this change at coherent-oss/pytest-flake8@739193d.

**Comment by das-g** [comment]
Has pytest-flake8 development moved to <https://github.com/coherent-oss/pytest-flake8>?

**Comment by jaraco** [comment]
Yes

**Comment by das-g** [comment]
Closing, as this has been merged in https://github.com/coherent-oss/pytest-flake8.

**Pull request closed without merging**
