### PR TITLE
Remove Python 2 support and dependency on py, fixes #81

### LINKED ISSUE #81: Flake 8 - StringIO wrapper error with [FLAKE8 - AttributeError: '_io.StringIO' object has no attribute 'buffer']
Installed flake through pipenv
```
$ pipenv install -d pytest
$ pipenv install -d flake8
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*
```
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.9.5",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.8.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.4.0"
    }
  ],
  "version": "4.0.1"
}
```
*Please describe the problem or feature*
I have a project where flake aparently works as intended, and when I use the commandline flake it still works to some extent without all the pytest.ini setup, but within the Pipenv project it fails through pytest when it finds an error.
I run flake8:
```
$ python -m pytest --flake8
```
In all other projects we have it works flawlessly, and I really like the tool :D
In general the error comes when the file contains an error and flake8 tries to write to stdout.

This is my pipfile (removed the internal libs, but they dont wrap output in any way:
```
... removed private pypis ...

[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
pytest = {version="*", index="pypi"}
pytest-flake8 = {version="*", index="pypi"}
pylint = {version="*", index="pypi"}
strenum = {version="*", index="pypi"}
... private libs ...
google-cloud-datastore = {version="*", index="pypi"}
geojson = {version="*", index="pypi"}
firebase_admin = "*"

[packages]

[requires]
python_version = "3.9"
```
checked the locks, and same lib versions as bug-report and:
pytest 6.2.5
pytest-flake8 1.0.7

We have the same setup in other projects without the same issue so I'm a bit confused.
I however suspect something wrap the stdout StringIO so the expected attributes are not accessible by flake when it needs to report its findings.

### PR DESCRIPTION
**Pull request by erikkemperman**
Hi,

I just ran into https://github.com/tholo/pytest-flake8/issues/81 and looked into it a bit.

It seems that the stderr/stdout capturing, currently handled by `py`, doesn't agree with `flake8` report generation...

Considering that `py` is in maintenance mode and Python 2 is officially pushing the daisies, I thought you might consider this PR which uses capturing utilities available in the standard library, `contextlib` -- since 3.4.

### CODE REVIEW

**Comment by erikkemperman** [comment]
Sorry, docs say that redirecting stdout was added in 3.4, but stderr was only added in 3.5 -- amended the commit, and threw in 3.10 for good measure.

**Comment by khink** [comment]
This looks like a good fix, well at least it seems to agree with the pytest maintainer's suggestion in https://github.com/PyCQA/flake8/pull/1422 ("use io.TextIOWrapper").

@tholo Do you have any reservations about this MR? Maybe some changes needed before it can be merged? People could help in getting these changes in, just let us know.

**Review by taliastocks — APPROVED** [review]
Love it.

**Comment by boidolr** [comment]
Would love this too 👍 
@erikkemperman I think a change to `.travis.yml` is needed too, to reflect the versions in the tests.

**Comment by erikkemperman** [comment]
@boidolr Thanks, I've amended the travis config now.

**Comment by erikkemperman** [comment]
Sorry for the force pushes, had not configured my gpg key properly on new laptop

**Comment by JulienPalard** [comment]
I tested this branch and it works for me.

**Pull request merged**
